name: Build LiteRoot OS ISO

on:
  workflow_dispatch:
    inputs:
      note:
        description: '构建备注（选填）'
        required: false
        default: 'Build LiteRoot Install ISO'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y live-build debootstrap squashfs-tools xorriso grub-pc-bin grub-efi-amd64-bin dosfstools gdisk rsync

      - name: Clean old build folder
        run: |
          rm -rf build
          mkdir -p build
          cp -r ./auto ./config ./build/

      - name: Build ISO image
        run: |
          cd build
          sudo lb clean
          sudo lb config
          sudo lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/*.iso
          name: LiteRoot-OS-x86_64
